### ISSUE TITLE
Holding Current Slope Analysis

### ISSUE THREAD

**Issue by swharden** [shengwanhui/Lab-Analysis#1]
**Can slow changes in holding current be measured using linear regression and compared across cells?** The purpose of this issue is to explore this question using Python. The main steps of this task well be:

### Setting-Up the Environment
- [x] Install Python ([Anaconda](https://www.anaconda.com/products/individual))
- [x] Install [VS Code](https://code.visualstudio.com/) and the [python extension](https://marketplace.visualstudio.com/items?itemName=ms-python.python)
- [x] Sync this repository on your local computer using [GitHub desktop](https://desktop.github.com/)
- [x] In the GitHub desktop client click "Repository" and select "Open in Visual Studio Code"
- [x] Confirm you can run `/src/ScottDemo.py`
- [x] Create your own sample program in `/src/WanhuiDemo.py` and ensure it runs
- [x] Use the GitHub desktop client to commit your file to the repository and push it to the cloud
- [x] Analyze an ABF in Origin, then save the memetest sheet as a CSV file in `/data/210224123.abf.csv`
- [x] Install the [Markdown Preview](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-preview-github-styles) plugin for VS code
- [x] Edit `/readme.md` and write something to indicate this repository is for personal projects and programming practice

### Ephys Project
- [x] Load data from a CSV file in Python (with numpy or pandas) and make a 2D scatter plot (with matplotlib)
- [x] Isolate the pre-drug current values as a new array and use the linear fit function to calculate its slope and intercept, then draw that fitted line on the plot. 
- [x] Use matplotlib's [axvspan()](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.axvspan.html) to lightly shade the baseline region. 
- [x] Create a second line fitted to the drug region, and similarly shade that portion of the plot
- [x] Put as much code as possible into methods so figures can be made just by supplying a file name and baseline/drug times
- [x] Use pyABF to read holding current from an ABF file instead of reading this data from the CSV files
- [x] Move all functions into custom modules so they're easy to access from a Jupyter notebook
- [x] Generate slope analysis images for Analyze every ABF in the project using a Jupyter notebook

**Comment by shengwanhui** [comment]
Have problem to install pandas by "import `pandas"` with the following error:
_ImportError: Unable to import required dependencies:
numpy:_'
These attempts were done: 
1. Upgraded python to 3.8.
2. Made sure Python version and pip version are both 3.8.
3. Installed pandas from anaconda navigator.

**Comment by swharden** [comment]
I'll take a look at your computer in person to get a better idea of what's going on 👍 

Try to run `/dev/plotting/demo.py` and `/dev/csv-files/demo.py` to see if both programs work for you. 

To run the CSV file demo you have to be in the same folder as `demo.py`. To do this open up the command prompt in Visual Studio code (`CTRL` + `~`), use `cd` to navigate to the folder containing that file, and run `demo.py`

If you get these two demos to work, you can combine their concepts into a new program in `/src` that makes a plot from membrane test data!

**Comment by swharden** [comment]
Hey @shengwanhui, awesome progress since last time! 🥳 I added two new examples in `/dev` to help you out.

### Locate Files and Folders

New python scripts we work on will probably have this at the top:

```python
import os
thisFolder = os.path.abspath(os.path.dirname(__file__))
```

By knowing what folder a python script is in, it's possible to locate things (like CSV files) relative to that python script, rather than relative to whatever folder you call `python.exe` from. This means CSV files can be read from and PNG files can be saved to the proper folders regardless of what folder you launch the python script from. Getting this right also means you can use the little play button at the top of VS Code to run your scripts, and they'll always get the paths right.

After you move your ih analysis script into `/src`, see if you can use this method to locate the CSV file so it works no matter what folder it's run from (including clicking the play button)

### Linear Regression

Linear regression with scipy is simpler than with sklearn, so let's use that for now. It's just one line! I put an example in `/dev/linear-regression`. Review the lines that interact with matplotlib, and see if you can understand what all the parts and arguments do. We will learn on matplotlib a lot, so learning it well will really help us move fast in future steps.

See if you can figure out how to do a linear regression for a portion of your Ih data using this method. You might hit some tricky spots, but let me know if you get stuck and we can take a look together! Good luck! 🚀

**Comment by swharden** [comment]
Hey @shengwanhui, your progress is looking awesome!

![Figure_1](https://user-images.githubusercontent.com/4165489/109578938-120eb880-7ac6-11eb-9f76-89d0ee6dbae4.png)

I added a few new examples to the `/dev` folder. Check out the ones from my last comment and these new ones, and you might have most of what you need to do this slope analysis on a lot of ABF files!

### Reading Ih from ABF Files

`/dev/abf` has an example of this. Let's keep it simple and call holding current the mean of the sweep values between seconds 2 and 10 (or something that sounds good to you).

### Use modules to prepare for Jupyter Notebook

Now that you're starting to make big and useful functions, look how _modules_ can be used to put functions in one file then `import` them for use in another file. `/dev/modules` has an example of this.

If you put your functions inside a `slopeAnalysis.py` file, we can write our code in another file and simply `import slopeAnalysis` at the top. Perhaps `abfTools.py` would be helpful for code that locates ABFs and reads their protocols. Putting functions inside modules is how we will be able to use all your code inside a Jupyter notebook! We can put all the logic in python files, and keep the notebook as simple as possible.

Let's try to use python files for all the development, and after everything is working our final step can be to generate a plot of every ABF in your project and show that output in a Jupyter notebook. That notebook's code might be as simple as:

```cs
import abfTools
import slopeAnalysis
slopeAbfPaths = abfTools.getAbfPaths(R"X:\some\path", protocol="0406", withTags=True)
for abfPath in slopeAbfPaths:
    slopeAnalysis.plotSlopes(abfPath, 0, 5, 5, 10)
```

...and the output would be dozens of graphs

### Reading protocol name from ABF files

`/dev/abf` has an example of this. This should make it easy to determine if an ABF is the type of ABF you want based on its protocol name. It's also possible to read the tag comments if you want to only analyze ABFs that have tags. The pyABF tutorial shows how to read comments: https://swharden.com/pyabf/tutorial

### Finding all ABF files in a folder with a certain protocol

`dev/iterating-files` shows how to find all ABF files in a folder. You can use this in the lab to point to a folder on the X-Drive, then make a list of all the files with a certain protocol. That list can be used to perform slope analysis on every ABF
